const actionTypes = {
  NEW_MOVE: "NEW_MOVE",
  CAPTURE_PIECE: "CAPTURE_PIECE",
  MOVE_CAPTURED: "MOVE_CAPTURED",
  CANDIDATE_MOVE: "CANDIDATE_MOVE",
  CLEAR_CANDIDATE_MOVE: "CLEAR_CANDIDATE_MOVE",
};

export default actionTypes;
